---
- name: Register Docker APT Key
  apt_key: keyserver=keyserver.ubuntu.com id=36A1D7869245C8950F966E92D8576A8BA88D21E9

- name: Register Docker Repository
  apt_repository: repo='deb https://get.docker.com/ubuntu docker main' state=present update_cache=yes

- name: Install Docker
  apt: name=lxc-docker state=present

- name: Register Vagrant User in Docker Group
  command: usermod -a -G docker vagrant

- name: Register dockerd Service
  template: src=../templates/dockerd.j2 dest=/etc/init.d/dockerd owner=root group=root mode="0755"

- name: Disable docker Service
  template: src=../templates/docker.override.j2 dest=/etc/init/docker.override owner=root group=root

- name: Enable dockerd Service
  command: sudo update-rc.d dockerd defaults
  notify:
  - Stop Docker
  - Restart Docker Daemon
