---
- name: Update Apt Cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install Prerequisites
  apt: name={{ item }} state=present
  with_items:
  - build-essential
  - cgroup-lite
  - git-core
  - htop
  - iotop
  - language-pack-en
  - linux-image-extra-{{ ansible_kernel }}
  - software-properties-common
  - vim
